In [2]:
import numpy as np

# Arrays

In [3]:
lst = [1,2,3]
x = np.array(lst)
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [5]:
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
# Check dimension
m.shape

(2, 3)

In [9]:
# Return evenly spaced values within a given interval
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
# Gives a new shape to an array without changing its data.
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [14]:
# Specify the range (0 to 4) and total number (9) and it'll split up the interval accordingly
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [15]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [20]:
# Returns an array of 1s, one dimensional
np.ones(2)

array([1., 1.])

In [23]:
# Returns an array of 1s, 2 dimensionals
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [25]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
y

array([4, 5, 6])

In [28]:
# Create diagonal array
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [29]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
# Repeat elements of an array, one at a time
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Operations

In [34]:
x

array([1, 2, 3])

In [36]:
y

array([4, 5, 6])

In [38]:
x + y

array([5, 7, 9])

In [39]:
x - y

array([-3, -3, -3])

In [40]:
x ** 2

array([1, 4, 9])

In [41]:
# Dot product
x.dot(y)

32

In [42]:
z = np.array([y, y ** 2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [44]:
z.shape

(2, 3)

In [45]:
# Transpose - swap rows and cols
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [46]:
z.T.shape

(3, 2)

In [47]:
z.dtype

dtype('int64')

In [48]:
# Cast to different type
z = z.astype('f')
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [49]:
a = np.array([-4, -2, 1, 3, 5])

In [52]:
a.sum()

3

In [53]:
a.max()

5

In [54]:
a.min()

-4

In [55]:
a.mean()

0.6

In [57]:
a.std()

3.2619012860600183

In [58]:
a.argmax() #index of the maximum

4

In [60]:
a.argmin() #index of the min

0

In [66]:
s = np.arange(13)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
s2 = np.arange(13) ** 2
s2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [68]:
s[0], s[4], s[-1]

(0, 4, 12)

In [70]:
# Use `:` to indicate a range. `array[start:stop]`
# Leaving start or stop empty will default to the beginning/end of the array.
s[1:5]

array([1, 2, 3, 4])

In [72]:
s[-5::-2] # Starting from the 5th item from the back, go backward and jump 2 at a time

array([8, 6, 4, 2, 0])

In [73]:
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [75]:
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
# array[row, col]
r[2,2]

14

In [78]:
r[3, 3:6] # 3rd row, range 3 to 6

array([21, 22, 23])

In [79]:
# selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [81]:
# last row, every other elements
r[-1, ::2]

array([30, 32, 34])

In [82]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [84]:
# assigning all values in the array that are greater than 30 to the value of 30
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copy data

In [85]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [86]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [87]:
# Modify r2 also modifies r
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [88]:
# To avoid this, use `r.copy` to create a copy that will not affect the original array
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [89]:
r_copy[:] = 10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [90]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Iterating Over Arrays

In [93]:
# 4 x 3 matrix of random numbers 0-9
test = np.random.randint(0, 10, (4,3))

In [94]:
test

array([[5, 7, 9],
       [2, 6, 2],
       [1, 9, 2],
       [5, 1, 8]])

In [95]:
for row in test:
    print(row)

[5 7 9]
[2 6 2]
[1 9 2]
[5 1 8]


In [96]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 7 9]
row 1 is [2 6 2]
row 2 is [1 9 2]
row 3 is [5 1 8]


In [98]:
test2 = test ** 2
test2

array([[25, 49, 81],
       [ 4, 36,  4],
       [ 1, 81,  4],
       [25,  1, 64]])

In [99]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[5 7 9] + [25 49 81] = [30 56 90]
[2 6 2] + [ 4 36  4] = [ 6 42  6]
[1 9 2] + [ 1 81  4] = [ 2 90  6]
[5 1 8] + [25  1 64] = [30  2 72]


In [100]:
# zip
integers = [1, 2, 3]
letters = ['a', 'b', 'c']
floats = [4.0, 5.0, 6.0]
zipped = zip(integers, letters, floats)  # Three input iterables
list(zipped)

[(1, 'a', 4.0), (2, 'b', 5.0), (3, 'c', 6.0)]

In [101]:
b = np.arange(36)
b.resize((6,6))

In [102]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [107]:
b.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [108]:
b[2:4, 2:4]

array([[14, 15],
       [20, 21]])